FROM node:20

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10.33.0 --activate

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --prod=false

COPY . .

RUN pnpm build

CMD ["pnpm", "worker:prod"]